FROM ubuntu:24.04
LABEL MAINTAINER "Alex Sierkov <alex.sierkov@gmail.com>"
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y tzdata screen sudo gnupg2 ca-certificates vim-nox less
RUN ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime
RUN dpkg-reconfigure --frontend noninteractive tzdata
RUN cp /etc/sudoers /etc/sudoers.orig
RUN awk '{ if (/^%sudo/) { print "%sudo\tALL=(ALL:ALL) NOPASSWD:ALL" } else { print } }' /etc/sudoers.orig > /etc/sudoers
RUN useradd -m -s /bin/bash -G sudo dev
RUN apt-get install -y build-essential cmake pkg-config gdb libboost1.83-all-dev libboost-url1.83-dev libsodium-dev libzstd-dev libssl-dev libfmt-dev libspdlog-dev
RUN mkdir /home/dev/dt
COPY 3rdparty /home/dev/dt/3rdparty
COPY src /home/dev/dt/src
COPY lib /home/dev/dt/lib
COPY etc /home/dev/dt/etc
COPY data /home/dev/dt/data
COPY test /home/dev/dt/test
COPY CMakeLists.txt /home/dev/dt
COPY publisher /home/dev/dt/publisher
COPY docker-test.sh /home/dev
RUN chown -R dev:dev /home/dev

USER dev
WORKDIR /home/dev/dt
RUN cmake -B cmake-build-release
RUN cmake --build cmake-build-release -j3 -t dt
RUN mkdir log
WORKDIR /home/dev/dt/cmake-build-release
ENV DT_LOG=/home/dev/dt/log/dt.log
CMD [ "/bin/bash", "/home/dev/docker-test.sh" ]